# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'testmission.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.

from dronekit import connect, VehicleMode, LocationGlobalRelative
import time
import argparse
from PyQt5 import QtCore, QtGui, QtWidgets

#parser = argparse.ArgumentParser(description='commands')
#parser.add_argument('--connect')
#args = parser.parse_args()
#connection_string = args.connect
vehicle = connect("tcp:127.0.0.1:5762", wait_ready=True)
vehicle.airspeed = 7

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(400, 300)
        self.label = QtWidgets.QLabel(Form)
        self.label.setGeometry(QtCore.QRect(40, 200, 311, 21))
        self.label.setText("")
        self.label.setObjectName("label")
        self.widget = QtWidgets.QWidget(Form)
        self.widget.setGeometry(QtCore.QRect(30, 20, 341, 121))
        self.widget.setObjectName("widget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.widget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.arm_takeoff = QtWidgets.QPushButton(self.widget)
        self.arm_takeoff.setObjectName("pushButton")
        self.arm_takeoff.clicked.connect(self.armTakeoff)
        self.horizontalLayout.addWidget(self.arm_takeoff)
        self.connect = QtWidgets.QPushButton(self.widget)
        self.connect.setObjectName("pushButton_5")
        self.horizontalLayout.addWidget(self.connect)
        self.wp1 = QtWidgets.QPushButton(self.widget)
        self.wp1.setObjectName("pushButton_2")
        self.horizontalLayout.addWidget(self.wp1)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.wp1.clicked.connect(self.goToWaypoint)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.rtl = QtWidgets.QPushButton(self.widget)
        self.rtl.setObjectName("pushButton_3")
        self.horizontalLayout_2.addWidget(self.rtl)
        self.rtl.clicked.connect(self.returnToLaunch)
        self.close = QtWidgets.QPushButton(self.widget)
        self.close.setObjectName("pushButton_4")
        self.horizontalLayout_2.addWidget(self.close)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.close.clicked.connect(self.closeVehicle)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "TestMission"))
        self.arm_takeoff.setText(_translate("Form", "Arm and takeoff"))
        self.connect.setText(_translate("Form", "Connect to sitl"))
        self.wp1.setText(_translate("Form", "Go to waypoint 1"))
        self.rtl.setText(_translate("Form", "Return to Launch"))
        self.close.setText(_translate("Form", "Close connection"))

    def armTakeoff(self):
        print("Arming drone")

        while not vehicle.is_armable:
            time.sleep(1)

        vehicle.mode = VehicleMode("GUIDED")
        vehicle.armed = True

        while not vehicle.armed: time.sleep(1)

        print("Takeoff")
        vehicle.simple_takeoff(10)

        while True:
            altitude = vehicle.location.global_relative_frame.alt

            if altitude >= 10 - 1:
                self.label.setText("Altitude reached")
                break

            time.sleep(1)

    def goToWaypoint(self):
        self.label.setText("go to waypoint1")
        wp1 = LocationGlobalRelative(35.9872609, -95.8753037, 10)
        vehicle.simple_goto(wp1)

    def returnToLaunch(self):
        self.label.setText("Coming back")
        vehicle.mode = VehicleMode("RTL")


    def closeVehicle(self):
        self.label.setText("Closing connection")
        vehicle.close()



if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
